name: agendamento_servicos
description: "Agendamento de serviços para oficinas mecânicas."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  test: ^1.21.0
  mockito: ^5.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true